### ISSUE TITLE
Error when a SSH connection is launched

### ISSUE THREAD

**Issue by cheshireca7** [nccgroup/ABPTTS#2]
Hello nccgroup,

I'm trying to establish a SSH connection like you do at the Quick Start - Apache Tomcat point in the manual. When I try to open the ssh connection through loopback, the abpttsclient thread show this error:

> [2019-02-10 16:51:25.232285] Connecting to 127.0.0.1:22 via http://10.0.2.10:8080/abptts.jsp
> [2019-02-10 16:51:25.243503] Server set cookie JSESSIONID=9B9155E5D0CE9F89255F6BE78DECFB3F; Path=/; HttpOnly
> [2019-02-10 16:51:25.243681] Error: could not create connection. Raw server response: 3ba5f2cf1aeb0e67b8eb123c6974adefa1743948747412cedaa3264b8d2f&1a487f
> [2019-02-10 16:51:25.243721] Unexpected state: child loop exited without closeConnections being set to 1

I am able to see the http://10.0.2.10:8080/abptts.jsp file from the attacker, so I guess the tomcat side is correct.

Any ideas? Thanks in advance.

Regards.

**Comment by blincoln682F048A** [comment]
Hi.

Are you sure you're using the same configuration on the client that matches the one in the JSP file that you uploaded? That error usually means that there's a mismatch between the configuration files.

**Comment by cheshireca7** [comment]
Solved! Just restored de machine and works. Thanks!!
